### ISSUE TITLE
Cambiar el texto de ver los caps.

### ISSUE THREAD

**Issue by SackVengador** [Acechanime/acecha#51]
Tanto en versión PC como móvil seria bueno que en donde aparecen todos los caps, en vez de poner Ver "Ejemplo" capitulo 1. Que ponga directamente "Ejemplo" 1. Porque en versión movil por ejemplo los nombres largos se ven muy feos. Al menos que ponga "Ejemplo" ep 1.

**Comment by Araozu** [comment]
Terminado.
